[package]
name = "docu"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
dirs = "6.0.0"
regex = "1.11.1"
once_cell = "1.21.3"
rusqlite = { version = "0.37.0", features = ["bundled"] }
thiserror = "2.0.12"
